//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeViewDataGrid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Office { get; set; }
        public string TitleOfCourtesy { get; set; }
        public Nullable<System.DateTime> BirthData { get; set; }
        public string HomePhone { get; set; }
        public int ReportsTo { get; set; }
    }
}
